create table if not exists customer (
  customer_id int generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(100) not null,
  mobile_number varchar(20) not null,
  created_by varchar(20) not null,
  updated_at date default null,
  updated_by varchar(20) default null
);

create table if not exists accounts (
  customer_id int not null,
  account_number int generated by default as identity primary key,
  branch_address varchar(100) not null,
  created_at date not null,
  created_by varchar(20) not null,
  updated_at date default null,
  updated_by varchar(20) default null
);
