spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "hehe QA"
  contact details:
    name: "Rohan Chhabra"
    email: "hehe"
  onCallSupport:
    - 0000000000
