spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to Bank cards related QA APIs "
  contactDetails:
    name: "QA Lead"
    email: "qa@eazybank.com"
  onCallSupport:
    - 0000000000